services:
  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: zola_france
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

volumes:
  postgis-data:

